# Generated by Django 3.0.4 on 2020-04-20 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='value',
        ),
        migrations.AddField(
            model_name='vote',
            name='vote',
            field=models.NullBooleanField(),
        ),
    ]
