# Generated by Django 3.0.4 on 2020-04-20 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0002_auto_20200420_2304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='vote',
            new_name='value',
        ),
    ]
